### ISSUE TITLE
2 CUDA-capable GPUs

### ISSUE THREAD

**Issue by HollisJoe** [ttykkala/recon#1]
What's your GPUs model? Thanks!

**Comment by ttykkala** [comment]
i have lenovo y510p laptop with dual geforce 755m cards

**Comment by HollisJoe** [comment]
Hi, What this error?
![image](https://user-images.githubusercontent.com/24452259/27419812-6255eb12-5755-11e7-9d4b-aed85803cbc3.png)
Thanks!
